### Recuperar todo los productos 
GET http://localhost:8080/products
### Recupera los productos con un limite por url 
GET http://localhost:8080/products?limit=3
### Recuperar los productos por su id
GET http://localhost:8080/products/2
### Recupera al no existir su codigo deuvelve un objeto con un mensaje error
POST http://localhost:4000/api/products
Content-Type: application/json

{
    "title": "producto nuevo",
    "description": "esta es la descripcion del producto nuevo",
    "price": 200,
    "code": "AABB123",
    "stock": 30,
    
}