### Recuperar todo los productos 
GET http://localhost:4000/api/products
### Recupera los productos con un limite por url 
GET http://localhost:4000/api/products?limit=2
### Recuperar los productos por su id
GET http://localhost:4000/api/products/2
### Recupera al no existir su codigo deuvelve un objeto con un mensaje error
POST http://localhost:4000/api/products
Content-Type: application/json

{
    "title": "Nuevo producto",
    "description": "esta es la descripcion del nuevo producto",
    "price": 200,
    "code": "AAB01a",
    "stock": 30,
    "thumbnails":
}
###
GET http://localhost:4000/api/cart
###
POST http://localhost:4000/api/cart
Content-Type: application/json

{
  "quantity": 
}
###
DELETE http://localhost:4000/api/products/d6a27d1351751222

